src/Entity/Commandes.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\CommandesRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: CommandesRepository::class)]
class Commandes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $numero_cmd = null;

    private ?string $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    private ?User $user = null;

    /**
     * @var Collection<int, CommandeDetails>
     */
    #[ORM\OneToMany(targetEntity: CommandeDetails::class, mappedBy: 'commandes', cascade: ['persist', 'remove'])]
    private Collection $commandeDetails;

    public function __construct()
    {
        $this->commandeDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroCmd(): ?string
    {
        return $this->numero_cmd;
    }

    public function setNumeroCmd(string $numero_cmd): static
    {
        $this->numero_cmd = $numero_cmd;

        return $this;
    }

    public function getCreatedAt(): ?string
    {
        return $this->created_at;
    }

    public function setCreatedAt(string $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, CommandeDetails>
     */
    public function getCommandeDetails(): Collection
    {
        return $this->commandeDetails;
    }

    public function addCommandeDetail(CommandeDetails $commandeDetail): static
    {
        if (!$this->commandeDetails->contains($commandeDetail)) {
            $this->commandeDetails->add($commandeDetail);
            $commandeDetail->setCommandes($this);
        }

        return $this;
    }

    public function removeCommandeDetail(CommandeDetails $commandeDetail): static
    {
        if ($this->commandeDetails->removeElement($commandeDetail)) {
            // set the owning side to null (unless already changed)
            if ($commandeDetail->getCommandes() === $this) {
                $commandeDetail->setCommandes(null);
            }
        }

        return $this;
    }
}

src/Controller/CommandesController.php
<?php

namespace App\Controller;

use App\Entity\Produits;
use App\Entity\Commandes;
use App\Entity\CommandeDetails;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\ProduitsRepository;
use App\Repository\CommandesRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\CommandeDetailsRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CommandesController extends AbstractController
{

    #[Route('/commandes', name: 'app_valider_commandes')]
    public function ajouterCommande(
        SessionInterface $session,
        ProduitsRepository $produitsRepository,
        EntityManagerInterface $em
    ): Response {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $panier = $session->get('panier', []);
        $commande = new Commandes();
        $commande->setUser($this->getUser());
        $commande->setNumeroCmd(uniqid());
        $total = 0;

        foreach ($panier as $item => $quantity) {
            $commande_details = new CommandeDetails();
            $produit = $produitsRepository->find($item);
            $prix = $produit->getPrice();
            $commande_details->setProduits($produit);
            $commande_details->setPrix($prix);
            $commande_details->setQuantite($quantity);
            $commande->addCommandeDetail($commande_details);
        }

        $em->persist($commande);
        $em->flush();

        $session->remove('panier');
        $this->addFlash('success', 'Votre commande a été validée avec succès');
        return $this->redirectToRoute('app_resume_commande');
    }

    #[Route('/resume-commandes', name: 'app_resume_commande')]
    public function resumeCommande(
        CommandesRepository $commandesRepository,
        CommandeDetailsRepository $commandeDetailsRepository
    ): Response {

        // Récupérer l'utilisateur connecté
        $user = $this->getUser();
        // Récupérer les commandes de l'utilisateur connecté
        $commandes = $commandesRepository->findBy(['user' => $user]);
        // Tableau des détails des commandes;
        $details_commande = [];
        // Initialisation du total
        $total = 0;

        // Parcourir les commandes
        foreach ($commandes as $commande) {
            $details = $commandeDetailsRepository->findBy(['commandes' => $commande]);
            // Ajouter les détails de la commande dans le tableau
            $details_commande[$commande->getId()] = $details;

            // Calculer le total
            foreach ($details as $detail) {
                $total += $detail->getPrix() * $detail->getQuantite();
            }
        }

        return $this->render('commandes/resume_commande.html.twig', [
            'commandes' => $commandes,
            'details_commande' => $details_commande,
            'total' => $total
        ]);
    }

    #[Route('/supprimer-commande/{id}', name: 'app_supprimer_commande', methods: ['POST'])]
    public function supprimerCommande(
        Request $request,
        Commandes $commandes,
        EntityManagerInterface $em
    ) {
        if ($this->isCsrfTokenValid('delete' . $commandes->getId(), $request->request->get('_token'))) {
            $em->remove($commandes);
            $em->flush();
            $this->addFlash('success', 'Commande supprimée avec succès');
        }
        return $this->redirectToRoute('app_produits_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/commandes/resume_commande.html.twig
{% extends 'base.html.twig' %}
{% block body %}
	{% if app.user.commandes|length > 0 %}
		<h2 class="text-center text-success">Détails de votre commande</h2>
		{% for commande in app.user.commandes %}
			<div class="container bg-white shadow p-3 mt-3 rounded">
				<p class="text-success">Référence de la commande :
					{{commande.numeroCmd}}</p>
				<p class="text-danger">Votre email :
					{{commande.user.email}}</p>
				<p class="text-success">Date de la commande :
					{{commande.createdAt|date('d/m/Y')}}</p>
				<form method="post" action="{{ path('app_supprimer_commande', {'id': commande.id}) }}" onsubmit="return confirm('Confirmer la suppression de la commande ?');">
					<input type="hiden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
					<button type="submit" class="btn btn-danger">Supprimer la commande</button>
				</form>
			</div>

			<div class="row bg-white p-3 rounded shadow mt-3 w-50 mx-auto">
				<h3 class="text-success text-center">Détails de votre commande</h3>
				{% for details in details_commande[commande.id] %}
					<div class="col-md-3 col-sm-12">
						<h4 class="text-info">{{details.produits.name}}</h4>
						<img src="{{ asset('uploads/images/' ~ details.produits.photos[0].name) }}" class="d-block w-50" alt="{{details.produits.name}}">
						<div class="text-info">Quantité :
							{{details.quantite}}</div>
						<h5 class="text-success mt-3">Prix :{{details.prix}} €</h5>
						{% set montant_total = details.prix * details.quantite %}
						<h4 class="text-warning">Sous-total : {{montant_total}}€</h4>
					</div>
				{% endfor %}
				<h2 class="text-uppercase text-success mt-3">TOTAL DE LA COMMANDE : {{total}} €</h2>
				<a href="{{path('app_paiement_stripe', {numero_cmd: commande.numeroCmd}) }}" class="btn btn-primary">Payer la commande</a>
			</div>
		{% endfor %}
	{% else %}
		<div class="container bg-white shadow p-3 mt-3 rounded">
			<h2 class="text-center text-danger">Aucune commande enregistrée</h2>
		</div>
	{% endif %}
{% endblock %}